
package Server.soap;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankingServicePortType", targetNamespace = "Server.soap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankingServicePortType {


    /**
     * 
     * @param parameters
     */
    @WebMethod(action = "TransferMoney")
    @Oneway
    public void transferMoney(
        @WebParam(name = "transferMoneyRequest", targetNamespace = "Server.soap", partName = "parameters")
        TransferMoneyRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns Server.soap.AuditResponse
     */
    @WebMethod(action = "Audit")
    @WebResult(name = "auditResponse", targetNamespace = "Server.soap", partName = "parameters")
    public AuditResponse audit(
        @WebParam(name = "auditRequest", targetNamespace = "Server.soap", partName = "parameters")
        AuditRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns Server.soap.GetAccountsResponse
     */
    @WebMethod(action = "GetAccounts")
    @WebResult(name = "getAccountsResponse", targetNamespace = "Server.soap", partName = "parameters")
    public GetAccountsResponse getAccounts(
        @WebParam(name = "getAccountsRequest", targetNamespace = "Server.soap", partName = "parameters")
        GetAccountsRequest parameters);

}
